import bcrypt from 'bcryptjs';

const data = {
    users: [
        {
            name: 'Lauren',
            email: 'admin@example.com',
            password: bcrypt.hashSync('123456'),
            isAdmin: true,
        },
        {
            name: 'Becca',
            email: 'becca@example.com',
            password: bcrypt.hashSync('123456'),
            isAdmin: false,
        },

    ],
    products: [
        {
            name: 'Beard Oil + Hyaluronic Serum',
            slug: 'beard-oil',
            category: 'Other',
            image: '/images/p2.png',
            price: 80, 
            countInStock: 0,
            brand: 'bklyn',
            rating: '5',
            numReviews: '10',
            description: 'Enter beard oil description',
            instructions: 'Enter instructions',
            ingredients: 'Enter beard oil ingredients',
        },
        {
            name: 'Cherry Enzyme Wash',
            slug: 'cherry-enzyme-wash',
            category: 'Cleansers', 
            image: '/images/p1.png', //679px x 829px
            price: 75,
            countInStock: 10,
            brand: 'bklyn',
            rating: '5',
            numReviews: '10',
            description: 'For all skin types.  This wash contains no SLS or harsh detergents.  This is an AHA clenaser with enzymes to remove dirt and impurities.',
            instructions: 'Enter instructions',
            ingredients: 'Aqua (water), Sodium Hydroxypropylsulfonate Laurylglucoside Crosspolymer, Sodium Methyl Cocoyl Taurate, Polyglyceryl-4 Caprate, Glycolic Acid, Sodium Cocoyl Hydrolyzed Amaranth Protein, Lactobacillus/Punica Granatum Fruit Ferment Extract, Gluconolactone, Sodium Hydroxypropylsulfonate Decylglucoside Crosspolymer, Glycerin,  Butyrospermum Parkii (Shea) Butter Extract, Glucosamine HCI, Fructooligosaccharides (D-beta), Prunus Serotina Bark Extract (Wild Cherry Bark Extract)',
        },
        {
            name: 'Blueberry Scrub',
            slug: 'blueberry-scrub',
            category: 'Cleansers', 
            image: '/images/p1.png', //679px x 829px
            price: 75,
            countInStock: 10,
            brand: 'bklyn',
            rating: '5',
            numReviews: '10',
            description: 'A milder scrub than the Raspberry polishing scrub, less abrasive and can be used more often if needed. Contains exfolliants and antioxidants like the Raspberry polishing scrub in a less abrasive formula.',
            instructions: 'Apply a thick layer to the skin and wash in a circular motion to activate the exfoliating jojoba beads.',
            ingredients: 'Aqua (water),  Milk caprilic/Capric triglycerides, Jojoba oil, Glycerin (vegetable), Simmondsia Chinensis (Jojoba) Seed Oil (beads). L-lactic acid, L- malic acid, L-salicylic acid, Rubus Idaeus (Raspberry) Fruit Extract Concentrate, Vaccinium Angustifolium (Blueberry) Fruit Extract concentrate,  Hamamelis Virginiana (Witch Hazel) extract,  Zea Mays (Corn) Kernel Meal, Xanthan gum, D-Glucuronic acid, Jasminum Officinale (Jasmine) Oil, Citrus Paradisi (Grapefruit) Oil,  Medica Limonum (Lemon) Peel Oil, Citrus Aurantifolia (Lime) Oil',
        },
        {
            name: 'Clarifying Herbal Cleanser',
            slug: 'herbal-cleanser',
            category: 'Cleansers',
            image: '/images/p1.png',
            price: 75,
            countInStock: 20,
            brand: 'bklyn',
            rating: '5',
            numReviews: '10',
            description: 'This is a gently yet effective, non-abrasive, alpha hydroxy, exfoliating cleanser that effectively reduces blemishes. The new technology, using AHA polymers, results in less skin irritation. The addition of beta-hydroxy acid polymer helps clear the skin of blemishes.',
            instructions: 'Squeeze two to three drops in the palm of damp hands, rub hands to create a lather, then proceed to cleanse your face and neck. Rinse with tepid water.',
            ingredients: 'Aqua (Water), soluble Butyrospermum parkii (Shea Butter), plant cellulose, succinic acid, Laurus nobilis leaf extract, methylated karate, Cocos Nucifera (Coconut) amino acids, glycolic acid polymer, salicylic acid polymer, Vaccinium Macrocarpon (Cranberry) extract, and beta-carotene.',
        },
        {
            name: 'Rasberry Polishing Scrub',
            slug: 'rasberry-polishing-scrub',
            category: 'Cleansers',
            image: '/images/p1.png',
            price: 75,
            countInStock: 20,
            brand: 'bklyn',
            rating: '5',
            numReviews: '10',
            description: 'Effectively polishes your skin by exfoliating surface dead skin cells, leaving your skin with a healthy shiny glow.',
            instructions: 'Use once or twice a week to aggressively exfoliate the skin. Dispense a quarter-sized amount into the palm of hand, gently work around face and neck for one to two minutes, or until the products has lost its moisture, and then rinse thoroughly with warm water. Ideally, this should be done while in the shower.',
            ingredients: 'Aqua (Water), Rubus occidentalis(raspberry fruit) concentrate, Simmondsia Chinensis (Jojoba) beads, L-lactic acid, blue Zea Mays (Corn) Kernel Meal, xanthan gum, D-glucronic acid, vegetable glycerin, salicylic acid, and Jasminum Officinale (Jasmine) alcohol extract',
        },
        {
            name: 'Scrub + Shine',
            slug: 'scrub-shine',
            category: 'Cleansers',
            image: '/images/p1.png',
            price: 75,
            countInStock: 20,
            brand: 'bklyn',
            rating: '5',
            numReviews: '10',
            description: 'This is a combination mask/scrub that will leave your skin feeling and looking fresh and glowing.',
            instructions: 'Apply a cake icing thick layer to skin after cleansing and leave on for five to fifteen minutes, then rub with water in a circular motion to activate the jojoba beads, to scrub and exfoliate the skin.',
            ingredients: 'Aqua (Water), Vegetable Glycerin, Milk Caprylic/Capric Triglycerides, Simmondsia Chinensis (Jojoba) Seed Oil, L-Lactic Acid, L-Malic Acid, L-Salicyclic Acid, Hamamelis Virginiana (witch hazel) Extract, Ananas Sativus (Pineapple) Fruit Enzymes, Xanthan Gum, Prunus Serotin(Wild Cherry) Bark Extract, Zeolyte,  Simmondsia Chinensis (Jojoba) Beads, Citrus grandis (grapefruit) seed extract,  Citrus medica limonum (Lemon) fruit extract, Citrus Aurantifolia (Lime) Fruit Extract',
        },
        {
            name: 'Extra Gentle Cleaner',
            slug: 'extra-gentle-cleanser',
            category: 'Cleansers',
            image: '/images/p1.png',
            price: 75,
            countInStock: 20,
            brand: 'bklyn',
            rating: '5',
            numReviews: '10',
            description: 'Ideal for sensitive skin, even rosacea and post-laser resurfacing, this extra gently cleanser soothes and protects while leaving your skin feeling fresh without irritation or dryness.',
            instructions: 'Squeeze two to three drops in the palm of damp hands, rub hands to create a lather, then proceed to cleanse your face and neck. Rinse with tepid water.',
            ingredients: 'Aqua (water), Sodium Hydroxypropylsulfonate Laurylglucoside Crosspolymer, Succinic Acid Sulfate, Sodium Methyl Cocoyl Taurate, Butyrospermum Parkii (Shea Butter), Polyglyceryl-4 Caprate, Decyl Glucoside, Aniba Rosaedora (Rosewood) Oil',
        },
        {
            name: 'Ultra Firm Peptide',
            slug: 'ultra-firm-peptide',
            category: 'Peptides',
            image: '/images/p1.png',
            price: 100,
            countInStock: 30,
            brand: 'bklyn',
            rating: '5',
            numReviews: '10',
            description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
            instructions: 'Enter instructions',
            ingredients: 'Enter ingredients',
        },
    ],
}

export default data;