const data = {
    products: [
        {
            name: 'Beard Oil + Hyaluronic Serum',
            slug: 'beard-oil',
            category: 'Serums',
            image: '/images/beard-oil-sample.png',
            price: 80,
            countInStock: 10,
            rating: '5',
            numReviews: '10',
            description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
        },
        {
            name: 'Cherry Enzyme Wash',
            slug: 'cherry-enzyme-wash',
            category: 'Facewash',
            image: '/images/cherry-enzyme-sample.png',
            price: 75,
            countInStock: 10,
            rating: '5',
            numReviews: '10',
            description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
        },
        {
            name: 'Acne Wash',
            slug: 'acne-wash',
            category: 'Facewash',
            image: '/images/acne-wash-sample.png',
            price: 75,
            countInStock: 20,
            rating: '5',
            numReviews: '10',
            description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
        },
        {
            name: 'Ultra Firm Peptide',
            slug: 'ultra-firm-peptide',
            category: 'Cream',
            image: '/images/peptide-sample.png',
            price: 100,
            countInStock: 30,
            rating: '5',
            numReviews: '10',
            description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
        },
    ],
}